apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - name: {{ .Release.Name }}-controller
          image: {{ .Values.app.image.repo }}/controller:{{ .Values.app.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: TAIPOWER_CRAWLER_ENDPOINT
              value: http://taipower:50051

---
apiVersion: v1
kind: Service
metadata:
  name: controller
spec:
  type: ClusterIP
  selector:
    app: controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
