apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: stage-db-secret
spec:
  encryptedData:
    DB_ORG: AgBGZs1+MtjMBZg1Ow/1PXkuNR4WSiqVvl3MBe+2NdmlG1emdpcHwUc1Ox0mbsq/EkwDk8+/XfSMgJd62lUleTV6T5FnZjKgyPuoQt0JTHGsReB1fkLzl3AXsBhTNo+V21m5MI5cxZW3P9R5rIz7ptTzBnLx2QvjV6MKlyYpiG//6GATfpB0ZAAI15AFpE6+XoCc2TyAirSFfbOn7Ru94uPlEhH7Fu/iV2gPUA7VmYpgv4G6BS8R3jyWau5E9MMNS7rhA9b5jhg9N7VgEAZTLclP8IvFia0meehQ05BdXoUXIYNoMWpfFCr1eZln8r5wNOKPSb2Yz9rRS8DP9oeHrRijVjUiytF3znwDXVx3gA/qQAqjwi1QpvfDtfQMrHANt5xYCup+JrolVS1Dgbb8vCCz/thy472DW9IJ9Oy7FrzcI6w/lF07ErPhZXN+6PaN8MjO2nwQ2FO9xkPKzglO+xEoaFy30GGGcB5493vYtHks8UK6tyAPjE4ET41DJp2BCcwYt+ub7IS/fgK5+QMmbVLX3iy27idZYzR0CMJYQn7d7Wjo3ORGdeVKB8ayHonRWuQm4p3zdhj6EhccZCGcly+1oVnSB0koXEZCVbpOQRyDfD1m7M35S6KculiUsNjf+orifuBVPS+oC1E9B9MehBSI5HLh62FMDtCpK65RyX9FWXge+YlCPePgagsIEc4eB6RSyxkrcHIJEPQbvn2Sn7CX
    DB_TOKEN: AgAYV37NAwDxGj4l2oGHB/unYUGSTkNjdSYeZ9O2DONU5kfe4LPutHSD5UdCwS3et3pzCQFNQL4ofwu7c6LDze2slI/bR5KCwxQHNP0LjLAJpH073NOWcoWGGdBHsgMbA0i22YH4zIEPpEKrs7yUkizhQRj0svNDgieAoy4Jgqv7gUCUqre/4N16MS7GfJwhYCrl1SsBXXLYh2+b9DK6LxYAn5YU8x93HJ9k+5ix50dFv+iYHMI4Kri6G308Jtfi21FXp6mWq6tVhD9YtmYt/9aL4ALcbXQwCmmH23pD8M6DNmrTWKGKDck/mSc5fIEMJ4ijUz/ivFa0agZJAE/LlhCqWzrlqjMvXIOwC6QKvq6eGvC3+d6GRSyeen5g/3E656DR1Bj4nKPg7msZRYqXJygfGaXfEHHkFE2e6a10F5LPeCUFVfPqgTOuilM776GE7z981M2nzzMsVp0Yi2LyChAHv44UHYkl63VvdL3NMc0IHsQj1hYBtR7Onc2qM9koB8g5qYSVl86ErRFMREqt8PAXAIn+i4x2sRhcaPYMgaRTXYQOl+icpRwrjxjocq5bk101uCUOKIiH/RXM1TCXKNM617GeNcrDV9jSyPKgc1RR2qU238otfz4FCf1VyjRg3bd7SWVWCUtb+24QLhqlxf3/4+K+5ufbF2aNaokiCWP8VuwFrKygJZ1AoKUnKDpmeGeG3006W42gXnexT7jPkzf1g6Diy2vzVuZJkYCqNXmROg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: stage-db-secret

